spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3308/main-db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      s3:
        enabled: true
      ses:
        enabled: false

redis-flag:
  enabled: true

s3:
  bucket:
    name: fitassist-dev-bucket

lucene:
  enabled: true

jws:
  sharedKey: jaskdfhaksfouwrja;sdf'jasdkfjskdfjge

rate-limiter:
  user-rate: 10000
  user-interval: 1
  key-rate: 10000
  key-interval: 1

app:
  frontend:
    url: http://localhost:5173
  email:
    from: ${EMAIL_FROM}

logging:
  level:
    root: INFO
