spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3308/main-db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      s3:
        enabled: true
      ses:
        enabled: false

redis-flag:
  enabled: true

s3:
  bucket:
    name: fitassist-dev-bucket

lucene:
  enabled: true

rate-limiter:
  user-rate: 10000
  user-interval: 1
  key-rate: 10000
  key-interval: 1

app:
  frontend:
    url: http://localhost:5173
  csrf:
    cookie-secure: false
  email:
    from: ${EMAIL_FROM}

cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:5174
    - http://localhost:4173

logging:
  level:
    root: INFO
